//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Vcl.Controls.hpp>
#include <Vcl.StdCtrls.hpp>
#include <Vcl.Forms.hpp>
#include <SHDocVw.hpp>
#include <Vcl.OleCtrls.hpp>
#include "SHDocVw_OCX.h"
#include <Web.HTTPApp.hpp>
#include <Vcl.Edge.hpp>
#include <WebView2.hpp>
#include <Winapi.ActiveX.hpp>
#include <Vcl.Buttons.hpp>
#include <Vcl.ComCtrls.hpp>
#include <Vcl.TitleBarCtrls.hpp>
#include <Vcl.ExtCtrls.hpp>
#include <Vcl.WinXPanels.hpp>
#include <Vcl.Menus.hpp>
#include <System.ImageList.hpp>
#include <Vcl.ImgList.hpp>
#include <Vcl.Imaging.pngimage.hpp>
#include <IdBaseComponent.hpp>
#include <IdComponent.hpp>
#include <IdHTTP.hpp>
#include <IdTCPClient.hpp>
#include <IdTCPConnection.hpp>
#include <Vcl.VirtualImage.hpp>
#include <Vcl.ControlList.hpp>
#include <Vcl.BaseImageCollection.hpp>
#include <Vcl.ImageCollection.hpp>
#include <Vcl.CheckLst.hpp>
#include <System.Actions.hpp>
#include <Vcl.ActnList.hpp>
#include <Vcl.WinXCtrls.hpp>
#include <Vcl.Dialogs.hpp>
#include <Vcl.Imaging.jpeg.hpp>
#include <IdExplicitTLSClientServerBase.hpp>
#include <IdFTP.hpp>
#include <Vcl.ActnColorMaps.hpp>
#include <Vcl.ActnMan.hpp>
#include <System.Notification.hpp>
#include <Vcl.Grids.hpp>
#include <Vcl.FileCtrl.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
	TBitBtn *BitBtn1;
	TPageControl *PageControl1;
	TTabSheet *TabSheet1;
	TTabSheet *TabSheet2;
	TPanel *Panel1;
	TLabel *Label2;
	TLabel *Label3;
	TLabel *Label4;
	TLabel *Label5;
	TLabel *Label6;
	TMainMenu *MainMenu1;
	TMenuItem *N2;
	TLabel *Label7;
	TLabel *Label8;
	TComboBox *ComboBox1;
	TBitBtn *BitBtn2;
	TLabel *Label1;
	TImage *Image2;
	TBitBtn *BitBtn3;
	TPanel *Panel2;
	TMenuItem *N1;
	TBitBtn *BitBtn4;
	TBitBtn *BitBtn5;
	TMenuItem *N3;
	TIdHTTP *IdHTTP1;
	TLabel *Label9;
	TLabel *Label10;
	TLabel *Label11;
	TLabel *Label12;
	TLabel *Label13;
	TLabel *Label14;
	TLabel *Label15;
	TLabel *Label16;
	TBitBtn *BitBtn6;
	TImageCollection *ImageCollection1;
	TCardPanel *CardPanel1;
	TCard *Card1;
	TCard *Card2;
	TComboBoxEx *ComboBoxEx1;
	TTrayIcon *TrayIcon1;
	TVirtualImage *VirtualImage13;
	TLabel *Label24;
	TLabel *Label25;
	TVirtualImage *VirtualImage14;
	TVirtualImage *VirtualImage15;
	TVirtualImage *VirtualImage16;
	TVirtualImage *VirtualImage17;
	TLabel *Label26;
	TLabel *Label27;
	TVirtualImage *VirtualImage18;
	TVirtualImage *VirtualImage19;
	TVirtualImage *VirtualImage20;
	TVirtualImage *VirtualImage21;
	TVirtualImage *VirtualImage22;
	TVirtualImage *VirtualImage23;
	TLabel *Label28;
	TLabel *Label29;
	TVirtualImage *VirtualImage24;
	TVirtualImage *VirtualImage25;
	TLabel *Label30;
	TLabel *Label31;
	TVirtualImage *VirtualImage26;
	TVirtualImage *VirtualImage27;
	TVirtualImage *VirtualImage28;
	TCard *Card3;
	TCard *Card4;
	TVirtualImage *VirtualImage33;
	TVirtualImage *VirtualImage34;
	TVirtualImage *VirtualImage35;
	TVirtualImage *VirtualImage36;
	TLabel *Label34;
	TLabel *Label35;
	TLabel *Label36;
	TLabel *Label37;
	TLabel *Label38;
	TLabel *Label39;
	TLabel *Label40;
	TLabel *Label41;
	TVirtualImage *VirtualImage37;
	TVirtualImage *VirtualImage38;
	TVirtualImage *VirtualImage39;
	TVirtualImage *VirtualImage40;
	TVirtualImage *VirtualImage41;
	TVirtualImage *VirtualImage42;
	TVirtualImage *VirtualImage43;
	TVirtualImage *VirtualImage44;
	TVirtualImage *VirtualImage45;
	TVirtualImage *VirtualImage46;
	TVirtualImage *VirtualImage47;
	TVirtualImage *VirtualImage48;
	TVirtualImage *VirtualImage49;
	TVirtualImage *VirtualImage50;
	TVirtualImage *VirtualImage51;
	TVirtualImage *VirtualImage52;
	TLabel *Label42;
	TLabel *Label43;
	TVirtualImage *VirtualImage53;
	TVirtualImage *VirtualImage54;
	TVirtualImage *VirtualImage55;
	TVirtualImage *VirtualImage56;
	TLabel *Label44;
	TLabel *Label45;
	TVirtualImage *VirtualImage57;
	TVirtualImage *VirtualImage58;
	TVirtualImage *VirtualImage59;
	TVirtualImage *VirtualImage60;
	TLabel *Label46;
	TLabel *Label47;
	TVirtualImage *VirtualImage61;
	TVirtualImage *VirtualImage62;
	TVirtualImage *VirtualImage63;
	TVirtualImage *VirtualImage64;
	TLabel *Label48;
	TLabel *Label49;
	TVirtualImage *VirtualImage65;
	TVirtualImage *VirtualImage66;
	TVirtualImage *VirtualImage67;
	TVirtualImage *VirtualImage68;
	TLabel *Label50;
	TLabel *Label51;
	TVirtualImage *VirtualImage77;
	TLabel *Label56;
	TLabel *Label57;
	TVirtualImage *VirtualImage78;
	TVirtualImage *VirtualImage79;
	TVirtualImage *VirtualImage80;
	TBitBtn *BitBtn9;
	TBitBtn *BitBtn10;
	TPanel *OnCardPanel1;
	TVirtualImage *VirtualImage1;
	TLabel *Label17;
	TLabel *Label19;
	TVirtualImage *VirtualImage2;
	TVirtualImage *VirtualImage3;
	TVirtualImage *VirtualImage4;
	TBitBtn *BitBtn7;
	TVirtualImage *VirtualImage5;
	TLabel *Label20;
	TLabel *Label21;
	TVirtualImage *VirtualImage6;
	TVirtualImage *VirtualImage7;
	TVirtualImage *VirtualImage8;
	TVirtualImage *VirtualImage12;
	TVirtualImage *VirtualImage11;
	TVirtualImage *VirtualImage10;
	TLabel *Label23;
	TLabel *Label22;
	TVirtualImage *VirtualImage9;
	TVirtualImage *VirtualImage29;
	TVirtualImage *VirtualImage76;
	TLabel *Label54;
	TLabel *Label55;
	TLabel *Label33;
	TLabel *Label32;
	TVirtualImage *VirtualImage30;
	TVirtualImage *VirtualImage31;
	TVirtualImage *VirtualImage32;
	TBitBtn *BitBtn8;
	TVirtualImage *VirtualImage73;
	TVirtualImage *VirtualImage74;
	TVirtualImage *VirtualImage75;
	TCard *Card5;
	TBitBtn *BitBtn11;
	TBitBtn *BitBtn12;
	TVirtualImage *VirtualImage69;
	TLabel *Label52;
	TLabel *Label53;
	TVirtualImage *VirtualImage70;
	TVirtualImage *VirtualImage71;
	TVirtualImage *VirtualImage72;
	TVirtualImage *VirtualImage81;
	TLabel *Label58;
	TLabel *Label59;
	TVirtualImage *VirtualImage82;
	TVirtualImage *VirtualImage83;
	TVirtualImage *VirtualImage84;
	TMemo *Memo2;
	TBitBtn *BitBtn13;
	TPanel *Panel3;
	TBitBtn *BitBtn14;
	TLabel *Label60;
	TBitBtn *BitBtn15;
	TComboBoxEx *ComboBoxEx2;
	TCardPanel *CardPanel2;
	TCard *Card6;
	TToggleSwitch *ToggleSwitch2;
	TToggleSwitch *ToggleSwitch3;
	TLabel *Label63;
	TLabel *Label64;
	TLabel *Label65;
	TLabel *Label66;
	TLabel *Label67;
	TLabel *Label72;
	TToggleSwitch *ToggleSwitch4;
	TLabel *Label61;
	TToggleSwitch *ToggleSwitch5;
	TToggleSwitch *ToggleSwitch6;
	TLabel *Label73;
	TToggleSwitch *ToggleSwitch7;
	TToggleSwitch *ToggleSwitch8;
	TToggleSwitch *ToggleSwitch9;
	TLabel *Label68;
	TToggleSwitch *ToggleSwitch10;
	TImage *Image3;
	TCard *Card7;
	TLabel *Label69;
	TToggleSwitch *ToggleSwitch11;
	TToggleSwitch *ToggleSwitch12;
	TLabel *Label71;
	TToggleSwitch *ToggleSwitch13;
	TLabel *Label74;
	TToggleSwitch *ToggleSwitch14;
	TLabel *Label77;
	TLabel *Label79;
	TToggleSwitch *ToggleSwitch15;
	TLabel *Label75;
	TToggleSwitch *ToggleSwitch16;
	TLabel *Label76;
	TLabel *Label78;
	TLabel *Label80;
	TToggleSwitch *ToggleSwitch17;
	TLabel *Label81;
	TToggleSwitch *ToggleSwitch18;
	TLabel *Label82;
	TToggleSwitch *ToggleSwitch19;
	TCard *Card8;
	TLabel *Label89;
	TToggleSwitch *ToggleSwitch24;
	TLabel *Label90;
	TToggleSwitch *ToggleSwitch25;
	TLabel *Label91;
	TToggleSwitch *ToggleSwitch26;
	TLabel *Label93;
	TToggleSwitch *ToggleSwitch28;
	TLabel *Label96;
	TToggleSwitch *ToggleSwitch31;
	TLabel *Label97;
	TCard *Card9;
	TLabel *Label86;
	TLabel *Label87;
	TLabel *Label88;
	TToggleSwitch *ToggleSwitch21;
	TToggleSwitch *ToggleSwitch22;
	TToggleSwitch *ToggleSwitch23;
	TToggleSwitch *ToggleSwitch32;
	TLabel *Label98;
	TLabel *Label62;
	TToggleSwitch *ToggleSwitch1;
	TLabel *Label85;
	TLabel *Label70;
	TToggleSwitch *ToggleSwitch33;
	TToggleSwitch *ToggleSwitch20;
	TButton *Button1;
	TLabel *Label83;
	TListBox *ListBox1;
	TButton *Button2;
	TButton *Button3;
	TOpenDialog *OpenDialog1;
	TPageControl *PageControl2;
	TTabSheet *TabSheet4;
	TPanel *Panel4;
	TTimer *Timer1;
	TTimer *Timer2;
	TPanel *Panel6;
	TLabel *Label101;
	TLabel *Label102;
	TVirtualImage *VirtualImage87;
	TLabel *Label103;
	TButton *Button4;
	TPanel *Panel7;
	TLabel *Label104;
	TLabel *Label105;
	TVirtualImage *VirtualImage88;
	TLabel *Label106;
	TButton *Button7;
	TVirtualImage *VirtualImage89;
	TImage *Image4;
	TLabel *Label107;
	TLabel *Label18;
	TPanel *Panel8;
	TLabel *Label108;
	TLabel *Label109;
	TVirtualImage *VirtualImage90;
	TLabel *Label110;
	TButton *Button8;
	TVirtualImage *VirtualImage93;
	TVirtualImage *VirtualImage94;
	TVirtualImage *VirtualImage95;
	TCardPanel *CardPanel3;
	TCard *Card10;
	TLabel *Label111;
	TLabel *Label112;
	TLabel *Label114;
	TButton *Button10;
	TSplitter *Splitter1;
	TVirtualImage *VirtualImage97;
	TVirtualImage *VirtualImage98;
	TButton *Button9;
	TMenuItem *N4;
	TVirtualImage *VirtualImage99;
	TCard *Card11;
	TStringGrid *StringGrid1;
	TLabel *Label123;
	TLabel *Label124;
	TButton *Button17;
	TSpeedButton *SpeedButton2;
	TButton *Button16;
	TTabSheet *TabUtils;
	TLabel *Label127;
	TCheckListBox *AppBox;
	TLabel *Label128;
	TButton *Button18;
	TButton *Button19;
	TButton *Button20;
	TMenuItem *N5;
	TTabSheet *SoftSheet;
	TVirtualImage *VirtualImage100;
	TMemo *Memo3;
	TLabel *Label129;
	TLabel *Label130;
	TVirtualImage *VirtualImage101;
	TCheckListBox *StepBox;
	TVirtualImage *VirtualImage102;
	TBitBtn *BitBtn16;
	TSpeedButton *SpeedButton3;
	TTimer *Timer3;
	TSpeedButton *SpeedButton4;
	TListBox *ListBox2;
	TBitBtn *BitBtn17;
	TVirtualImage *VirtualImage103;
	TLabel *Label132;
	TEdit *Edit1;
	TSpeedButton *SpeedButton6;
	TSpeedButton *SpeedButton7;
	TImage *Image1;
	TPanel *Panel9;
	TPanel *Panel10;
	TPanel *Panel11;
	TLabel *Label131;
	TLabel *Label133;
	TButton *Button21;
	TLabel *Label134;
	TLabel *Label135;
	TButton *Button22;
	TLabel *Label136;
	TLabel *Label137;
	TButton *Button23;
	TCheckListBox *CleanBox;
	TLabel *Label113;
	TLabel *Label115;
	TLabel *Label116;
	TButton *Button11;
	TProgressBar *ProgressBar1;
	TButton *Button12;
	TButton *Button13;
	TButton *Button14;
	TOpenDialog *OpenDialog2;
	TLabel *Label117;
	TMemo *Memo1;
	TLabel *Label118;
	TTabSheet *ServTab;
	TVirtualImage *VirtualImage96;
	TLabel *Label119;
	TComboBox *ComboBox2;
	TStringGrid *ServGrid;
	TLabel *Label120;
	TLabel *Label121;
	TMemo *Memo4;
	TButton *Button15;
	TButton *Button24;
	TButton *Button25;
	TButton *Button26;
	TButton *Button27;
	TVirtualImage *VirtualImage104;
	TTabSheet *DefTab;
	TVirtualImage *VirtualImage85;
	TLabel *Label84;
	TVirtualImage *VirtualImage91;
	TButton *Button5;
	TLabel *Label94;
	TLabel *Label122;
	TMemo *Memo5;
	TMenuItem *N6;
	TMenuItem *N7;
	TMenuItem *N8;
	TVirtualImage *VirtualImage105;
	TLabel *Label92;
	TLabel *Label125;
	TLabel *Label126;
	TButton *Button28;
	TVirtualImage *VirtualImage106;
	TComboBox *ComboBox3;
	TLabel *Label138;
	TButton *Button29;
	TPanel *Panel12;
	TVirtualImage *VirtualImage107;
	TLabel *Label139;
	TLabel *Label140;
	TLabel *Label141;
	TVirtualImage *VirtualImage108;
	TButton *Button30;
	TMenuItem *N9;
	TMenuItem *N10;
	TMenuItem *English1;
	TTabSheet *TabUpdate;
	TVirtualImage *VirtualImage109;
	TLabel *Label142;
	TVirtualImage *VirtualImage110;
	TLabel *Label143;
	TLabel *Label144;
	TButton *Button31;
	TLabel *Label145;
	TLabel *Label146;
	TLabel *Label147;
	TLabel *Label148;
	TLabel *Label149;
	TLabel *Label150;
	TToggleSwitch *ToggleSwitch27;
	TToggleSwitch *ToggleSwitch29;
	TToggleSwitch *ToggleSwitch30;
	TToggleSwitch *ToggleSwitch34;
	TToggleSwitch *ToggleSwitch35;
	TButton *Button32;
	TButton *Button33;
	TButton *Button34;
	TVirtualImage *VirtualImage111;
	TBitBtn *BitBtn18;
	TButton *Button6;
	TVirtualImage *VirtualImage86;
	TButton *Button35;
	TButton *Button36;

	void __fastcall Button1Click(TObject *Sender);
	void __fastcall BitBtn1Click(TObject *Sender);
	void __fastcall BitBtn2Click(TObject *Sender);
	void __fastcall BitBtn3Click(TObject *Sender);
	void __fastcall BitBtn5Click(TObject *Sender);
	void __fastcall N3Click(TObject *Sender);
	void __fastcall N1Click(TObject *Sender);
	void __fastcall BitBtn4Click(TObject *Sender);
	void __fastcall Label11Click(TObject *Sender);
	void __fastcall Label11MouseLeave(TObject *Sender);
	void __fastcall Label11MouseEnter(TObject *Sender);
	void __fastcall Label14Click(TObject *Sender);
	void __fastcall Label15Click(TObject *Sender);
	void __fastcall Label16Click(TObject *Sender);
	void __fastcall PageControl1MouseMove(TObject *Sender, TShiftState Shift, int X,
          int Y);
	void __fastcall Label14MouseEnter(TObject *Sender);
	void __fastcall Label14MouseLeave(TObject *Sender);
	void __fastcall Label15MouseEnter(TObject *Sender);
	void __fastcall Label15MouseLeave(TObject *Sender);
	void __fastcall Label16MouseEnter(TObject *Sender);
	void __fastcall Label16MouseLeave(TObject *Sender);
	void __fastcall BitBtn6Click(TObject *Sender);
	void __fastcall ComboBoxEx1Change(TObject *Sender);
	void __fastcall VirtualImage16Click(TObject *Sender);
	void __fastcall VirtualImage14Click(TObject *Sender);
	void __fastcall VirtualImage20Click(TObject *Sender);
	void __fastcall VirtualImage18Click(TObject *Sender);
	void __fastcall VirtualImage21Click(TObject *Sender);
	void __fastcall VirtualImage28Click(TObject *Sender);
	void __fastcall VirtualImage26Click(TObject *Sender);
	void __fastcall BitBtn7Click(TObject *Sender);
	void __fastcall BitBtn8Click(TObject *Sender);
	void __fastcall VirtualImage30Click(TObject *Sender);
	void __fastcall VirtualImage73Click(TObject *Sender);
	void __fastcall VirtualImage75Click(TObject *Sender);
	void __fastcall ScrollBar1Change(TObject *Sender);
	void __fastcall VirtualImage3Click(TObject *Sender);
	void __fastcall VirtualImage2Click(TObject *Sender);
	void __fastcall VirtualImage74Click(TObject *Sender);
	void __fastcall VirtualImage31Click(TObject *Sender);
	void __fastcall VirtualImage12Click(TObject *Sender);
	void __fastcall VirtualImage10Click(TObject *Sender);
	void __fastcall VirtualImage8Click(TObject *Sender);
	void __fastcall VirtualImage37Click(TObject *Sender);
	void __fastcall VirtualImage42Click(TObject *Sender);
	void __fastcall VirtualImage45Click(TObject *Sender);
	void __fastcall VirtualImage44Click(TObject *Sender);
	void __fastcall VirtualImage46Click(TObject *Sender);
	void __fastcall VirtualImage48Click(TObject *Sender);
	void __fastcall VirtualImage78Click(TObject *Sender);
	void __fastcall VirtualImage49Click(TObject *Sender);
	void __fastcall VirtualImage50Click(TObject *Sender);
	void __fastcall VirtualImage54Click(TObject *Sender);
	void __fastcall VirtualImage53Click(TObject *Sender);
	void __fastcall VirtualImage55Click(TObject *Sender);
	void __fastcall VirtualImage58Click(TObject *Sender);
	void __fastcall VirtualImage57Click(TObject *Sender);
	void __fastcall VirtualImage59Click(TObject *Sender);
	void __fastcall VirtualImage62Click(TObject *Sender);
	void __fastcall VirtualImage63Click(TObject *Sender);
	void __fastcall VirtualImage61Click(TObject *Sender);
	void __fastcall VirtualImage67Click(TObject *Sender);
	void __fastcall PageControl1Change(TObject *Sender);
	void __fastcall VirtualImage72Click(TObject *Sender);
	void __fastcall VirtualImage71Click(TObject *Sender);
	void __fastcall VirtualImage70Click(TObject *Sender);
	void __fastcall BitBtn13Click(TObject *Sender);
	void __fastcall BitBtn15Click(TObject *Sender);
	void __fastcall ToggleSwitch2Click(TObject *Sender);
	void __fastcall ToggleSwitch1Click(TObject *Sender);
	void __fastcall ToggleSwitch3Click(TObject *Sender);
	void __fastcall ToggleSwitch4Click(TObject *Sender);
	void __fastcall ToggleSwitch5Click(TObject *Sender);
	void __fastcall ToggleSwitch6Click(TObject *Sender);
	void __fastcall ToggleSwitch7Click(TObject *Sender);
	void __fastcall ToggleSwitch8Click(TObject *Sender);
	void __fastcall ToggleSwitch9Click(TObject *Sender);
	void __fastcall ToggleSwitch10Click(TObject *Sender);
	void __fastcall ComboBoxEx2Change(TObject *Sender);
	void __fastcall ToggleSwitch11Click(TObject *Sender);
	void __fastcall ToggleSwitch12Click(TObject *Sender);
	void __fastcall ToggleSwitch13Click(TObject *Sender);
	void __fastcall ToggleSwitch14Click(TObject *Sender);
	void __fastcall ToggleSwitch15Click(TObject *Sender);
	void __fastcall ToggleSwitch16Click(TObject *Sender);
	void __fastcall ToggleSwitch17Click(TObject *Sender);
	void __fastcall ToggleSwitch18Click(TObject *Sender);
	void __fastcall ToggleSwitch19Click(TObject *Sender);
	void __fastcall ToggleSwitch32Click(TObject *Sender);
	void __fastcall ToggleSwitch24Click(TObject *Sender);
	void __fastcall ToggleSwitch25Click(TObject *Sender);
	void __fastcall ToggleSwitch33Click(TObject *Sender);
	void __fastcall ToggleSwitch26Click(TObject *Sender);
	void __fastcall ToggleSwitch28Click(TObject *Sender);
	void __fastcall ToggleSwitch31Click(TObject *Sender);
	void __fastcall ToggleSwitch20Click(TObject *Sender);
	void __fastcall ToggleSwitch21Click(TObject *Sender);
	void __fastcall ToggleSwitch22Click(TObject *Sender);
	void __fastcall ToggleSwitch23Click(TObject *Sender);
	void __fastcall Button2Click(TObject *Sender);
	void __fastcall Button3Click(TObject *Sender);
	void __fastcall Button4Click(TObject *Sender);
	void __fastcall Button5Click(TObject *Sender);
	void __fastcall Button6Click(TObject *Sender);
	void __fastcall Image3Click(TObject *Sender);
	void __fastcall Timer1Timer(TObject *Sender);
	void __fastcall BitBtn9Click(TObject *Sender);
	void __fastcall Timer2Timer(TObject *Sender);
	void __fastcall Image4Click(TObject *Sender);
	void __fastcall Button7Click(TObject *Sender);
	void __fastcall BitBtn16Click(TObject *Sender);
	void __fastcall VirtualImage89Click(TObject *Sender);
	void __fastcall Button8Click(TObject *Sender);
	void __fastcall Button9Click(TObject *Sender);
	void __fastcall VirtualImage91Click(TObject *Sender);
	void __fastcall VirtualImage92Click(TObject *Sender);
	void __fastcall VirtualImage93Click(TObject *Sender);
	void __fastcall VirtualImage94Click(TObject *Sender);
	void __fastcall VirtualImage95Click(TObject *Sender);
	void __fastcall BitBtn10Click(TObject *Sender);
	void __fastcall Button10Click(TObject *Sender);
	void __fastcall Button11Click(TObject *Sender);
	void __fastcall Button13Click(TObject *Sender);
	void __fastcall Button12Click(TObject *Sender);
	void __fastcall Button14Click(TObject *Sender);
	void __fastcall Button15Click(TObject *Sender);
	void __fastcall VirtualImage97Click(TObject *Sender);
	void __fastcall VirtualImage98Click(TObject *Sender);
	void __fastcall SpeedButton1Click(TObject *Sender);
	void __fastcall N4Click(TObject *Sender);
	void __fastcall Label121MouseMove(TObject *Sender, TShiftState Shift, int X, int Y);
	void __fastcall Label121MouseLeave(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall Timer3Timer(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall Button17Click(TObject *Sender);
	void __fastcall ListFiles(String dpath);
	void __fastcall SpeedButton2Click(TObject *Sender);
	void __fastcall Button16Click(TObject *Sender);
	void __fastcall TabUtilsShow(TObject *Sender);
	void __fastcall Button19Click(TObject *Sender);
	void __fastcall Button20Click(TObject *Sender);
	void __fastcall Button18Click(TObject *Sender);
	void __fastcall N5Click(TObject *Sender);
	void __fastcall VirtualImage100Click(TObject *Sender);
	void __fastcall SoftSheetShow(TObject *Sender);
	void __fastcall SpeedButton3Click(TObject *Sender);
	void __fastcall SpeedButton4Click(TObject *Sender);
	void __fastcall VirtualImage103Click(TObject *Sender);
	void __fastcall StepsFind(String dpath,String key1,int k1);
	void __fastcall SpeedButton7Click(TObject *Sender);
	void __fastcall SpeedButton6Click(TObject *Sender);
	void __fastcall Edit1KeyDown(TObject *Sender, WORD &Key, TShiftState Shift);
    void __fastcall SearchBig(String spath);
	void __fastcall Label117Click(TObject *Sender);
	void __fastcall Label117MouseEnter(TObject *Sender);
	void __fastcall Label117MouseLeave(TObject *Sender);
	void __fastcall Button22Click(TObject *Sender);
	void __fastcall AppBoxClick(TObject *Sender);
	void __fastcall StepBoxClick(TObject *Sender);
	void __fastcall VirtualImage104Click(TObject *Sender);
	void __fastcall ServTabShow(TObject *Sender);
	void __fastcall ServGridClick(TObject *Sender);
	void __fastcall ComboBox2Change(TObject *Sender);
	void __fastcall Button24Click(TObject *Sender);
	void __fastcall ServGridSelectCell(TObject *Sender, int ACol, int ARow, bool &CanSelect);
	void __fastcall Button25Click(TObject *Sender);
	void __fastcall Button27Click(TObject *Sender);
	void __fastcall Button26Click(TObject *Sender);
	void __fastcall N6Click(TObject *Sender);
	void __fastcall Button28Click(TObject *Sender);
	void __fastcall ComboBox3Change(TObject *Sender);
	void __fastcall Button29Click(TObject *Sender);
	void __fastcall Button30Click(TObject *Sender);
	void __fastcall English1Click(TObject *Sender);
	void __fastcall N10Click(TObject *Sender);
	void __fastcall VirtualImage111Click(TObject *Sender);
	void __fastcall ToggleSwitch27Click(TObject *Sender);
	void __fastcall ToggleSwitch29Click(TObject *Sender);
	void __fastcall ToggleSwitch30Click(TObject *Sender);
	void __fastcall ToggleSwitch34Click(TObject *Sender);
	void __fastcall ToggleSwitch35Click(TObject *Sender);
	void __fastcall Button32Click(TObject *Sender);
	void __fastcall Button34Click(TObject *Sender);
	void __fastcall Button33Click(TObject *Sender);
	void __fastcall BitBtn18Click(TObject *Sender);
	void __fastcall Button35Click(TObject *Sender);
	void __fastcall VirtualImage86Click(TObject *Sender);
	void __fastcall Button36Click(TObject *Sender);
	void __fastcall TabSheet2Show(TObject *Sender);









private:	// User declarations
public:		// User declarations
	__fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
